M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Wed 19 Oct 2022 11:41:32 PM -05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-19T23:41:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
%
G90
G05
T1
X3.9398Y-1.0945
X3.9449Y-2.7874
X6.4409Y-2.7953
X6.4488Y-1.1102
T0
M30
