M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Thu 20 Oct 2022 12:31:20 AM -05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-20T00:31:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.328Y-2.6965
X4.3307Y-5.8819
X6.6902Y-2.6965
X6.6929Y-5.8819
T0
M30
