#!/usr/bin/bash


anounce_file_upload(){
    echo "Uploading file $1 to esp32..."
}

sudo chmod a+rw /dev/ttyACM0

#-----------------------------------------------------#
#              Uploads utils and dependencies         #
#-----------------------------------------------------#
anounce_file_upload "./internet_connection.py"
anounce_file_upload "./time_management_module.py"
anounce_file_upload "./urequests.py"
anounce_file_upload "./umqttsimple.py"
anounce_file_upload "./mqtt_wrapper.py"
anounce_file_upload "./config.json"
ampy --port /dev/ttyACM0 put utils


#-----------------------------------------------------#
#              Uploads other base classes             #
#-----------------------------------------------------#
anounce_file_upload "./actuators_module.py"
anounce_file_upload "./sensors_module.py"
anounce_file_upload "./initialize_modules.py"
ampy --port /dev/ttyACM0 put modules


#-----------------------------------------------------#
#              Uploads integration class              #
#-----------------------------------------------------#
anounce_file_upload "./scheduler.py"
ampy --port /dev/ttyACM0 put ./scheduler.py


#-----------------------------------------------------#
#              Uploads boot and main                  #
#-----------------------------------------------------#

anounce_file_upload "./boot.py"
ampy --port /dev/ttyACM0 put ./boot.py

anounce_file_upload "./main.py"
ampy --port /dev/ttyACM0 put ./main.py


