M48
; DRILL file {KiCad 6.0.7+dfsg-1+b1} date Fri 30 Sep 2022 03:09:58 PM -05
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-30T15:09:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7+dfsg-1+b1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.328Y-2.6965
X4.3307Y-5.8819
X6.6902Y-2.6965
X6.6929Y-5.8819
T0
M30
